# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  test:
    cmds:
      - go test -v -count=1 -race -failfast ./...
      - cd examples/accounting && go run .

  fix:
    cmds:
      - goimports -v -w -local "$(go list -m)" .

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run staticcheck
    cmds:
      - staticcheck ./...

  vuln:
    desc: Run govulncheck for known vulnerabilities
    cmds:
      - govulncheck ./...

  check:
    desc: Run all static analysis (vet, lint, vuln)
    cmds:
      - task: vet
      - task: lint
      - task: vuln

  loadtest:
    env:
      N: 20000  # total operations
      B: 2000   # batch size
      BACKEND: nats
    cmds:
      - go run ./examples/loadtest/

  default:
    cmds:
      - task: test
      - task: fix
      - task: check
