# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  test:
    cmds:
      - go test -v -count=1 -race -failfast ./...

  fix:
    cmds:
      - goimports -v -w -local "$(go list -m)" .

  loadtest:
    env:
      N: 20000  # total events
      B: 2000   # batch size
      BACKEND: nats
    cmds:
      - go run ./cmd/loadtest/

  default:
    cmds:
      - task: test
      - task: fix
